name: "Code Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@4e08f1c6c3d3e9e7e8e6e6e6e6e6e6e6e6e6e6

    - name: Set up Python
      uses: actions/setup-python@5d8e1c6c3d3e9e7e8e6e6e6e6e6e6e6e6e6e6e6
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --require-hashes -r chainguard/requirements.txt
        pip install --require-hashes -r src/requirements.txt

    - name: Run security checks
      run: |
        bandit -r .
        safety check
