name: "Code Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@4e08f1c6c3d3e9e7e8e6e6e6e6e6e6e6e6e6e6

    - name: Set up Python
      uses: actions/setup-python@5d8e1c6c3d3e9e7e8e6e6e6e6e6e6e6e6e6e6e6
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
# chainguard/requirements.txt

Flask==3.1.1 --hash=sha256:07aae2bb5eaf77993ef57e357491839f5fd9f4dc281593a81a9e4d79a24f295c
redis==6.1.0 --hash=sha256:3b72622f3d3a89df2a6041e82acd896b0e67d9f54e9bcd906d091d23ba5219f6
prometheus-client==0.21.1 --hash=sha256:594b45c410d6f4f8888940fe80b5cc2521b305a1fafe1c58609ef715a001f301
Werkzeug==3.1.3 --hash=sha256:54b78bf3716d19a65be4fceccc0d1d7b89e608834989dfae50ea87564639213e

# …rest of your requirements…

    - name: Run security checks
      run: |
        bandit -r .
        safety check
