name: Image digest update

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permissão para escrever no repositório
      pull-requests: write # Permissão para abrir PRs
      id-token: write # Necessário para solicitar o JWT (JSON Web Token)

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: chainguard-dev/digestabot@cee67ce333549107c469dbe7656afda5a1e1f287 # v1.2.1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        signoff: true 
        author: "Natália Granato <nataliagranato@ufmg.br>" 
        committer: "Natália Granato <nataliagranato@ufmg.br>" 
        labels-for-pr: automated pr, kind/cleanup, release-note-none 
        branch-for-pr: update-digests 
        title-for-pr: Update images digests
